<div class="list-group">

    <?php foreach ($menu as $m): ?>
        <?php if(isset($id)): ?>
            <?php $_style = 'list-group-item active'; ?>
        <?php else: ?>
            <?php $_style = 'list-group-item'; ?>
        <?php endif ?>

        <a href="<?php echo $m['enlace']; ?>" class="<?php echo $_style; ?>"> <?php echo $m['titulo']; ?></a>
        

    <?php endforeach; ?>

</div>
