<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?=BASE_URL?>"><?=APP_NAME?></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <?php if(isset($menu) && sizeof($menu) > 0): ?>
            <div class="nav-collapse">
                <ul class="nav navbar-nav">
                    <?php foreach($menu as $item): ?>
                        <?php 
                        $_item_style = '';
                        
                        if(View::getViewId() && $item['id'] == View::getViewId())
                        {
                            $_item_style = 'active';
                        }
                        ?>

                        <li class="<?=$_item_style?>"><a  href="<?=$item['enlace']?>"><i class="<?=$item['imagen']?> <?=  isset($inverse) ? 'icon-white' : ''?>"> </i> <?=$item['titulo']?></a></li>
                    <?php endforeach; ?>
                </ul>

                <?php if(Session::get('autenticado')): ?>
                    <div class="navbar-form pull-right">
                        <a href="<?=BASE_URL?>usuarios/login/cerrar" class="btn  btn-default"><i class="icon-fire"> </i> Salir</a>
                    </div>
                <?php else: ?>
                    <form class="navbar-form pull-right" method="post" action="<?=BASE_URL?>usuarios/login">
                    
                        <input type="hidden" value="1" name="enviar">
                        <div class="form-group"><input class="form-control" name="usuario" type="text" placeholder="Usuario"></div>
                        <div class="form-group"><input class="form-control" name="pass" type="password" placeholder="Password"></div>
                        <button type="submit" class="btn btn-default">Entrar</button>
                    </form>
                <?php endif; ?>

            </div>
        <?php endif; ?>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>